import { Plugin } from 'vite'

import { StoryLiteUserConfig } from '@/types'

const defaultConfig: StoryLiteUserConfig = {
  title: 'StoryLite',
  stories: 'stories/**/*.stories.tsx',
  defaultStory: 'index',
  styleImports: {
    ui: [],
    sandbox: [],
  },
}

const generateConfigCode = (
  userConfig?: StoryLiteUserConfig,
): { config: StoryLiteUserConfig; code: string } => {
  const code = `
  // generated by storylite
  
  const defaultConfig = ${JSON.stringify(defaultConfig)}
  const userConfig = ${JSON.stringify(userConfig ?? {})}
  const resolvedConfig = { ...defaultConfig, ...userConfig }
  
  export default resolvedConfig
`

  return {
    config: { ...defaultConfig, ...userConfig },
    code,
  }
}

const createCssBundleCode = (cssFiles: string[]) => {
  // import all as inline and export a concat of them:
  const cssImports = cssFiles
    .map((cssFile, idx) => `import css${idx} from '${cssFile}?inline'`)
    .join('\n')

  const cssExports = cssFiles.map((cssFile, idx) => `css${idx}`).join(' + ')

  const cssVarDeclaration = `const cssConcat = ${cssExports.length > 0 ? cssExports : '""'};`

  return `${cssImports}\n${cssVarDeclaration}\nexport default cssConcat`
}

const moduleNames = {
  userConfig: 'storylite-user-config',
  userStories: 'storylite-user-stories',
  userUiStyles: 'storylite-user-styles-ui',
  userSandboxStyles: 'storylite-user-styles-sandbox',
}

const storylitePlugin = (userConfig?: StoryLiteUserConfig): Plugin => {
  const { config: storyliteConfig, code: storyliteConfigImportCode } =
    generateConfigCode(userConfig)
  // Define the file pattern to match
  const moduleIds = Object.values(moduleNames)

  return {
    name: 'import-stories',
    resolveId(id) {
      if (moduleIds.includes(id)) {
        return id // return the exact same ID, so Vite knows how to resolve it
      }

      return null // otherwise, return null to let Vite handle the import as usual
    },

    async load(id) {
      if (id === moduleNames.userStories) {
        // the returned code can only be JS
        return `
          const createStoryMap = (stories) => {
            const sortedStories = Object.entries(stories)
              .sort(([aName], [bName]) => aName.localeCompare(bName))
              .sort(([, { default: aStory }], [, { default: bStory }]) => {
                const aPriority = aStory?.priority || 0;
                const bPriority = bStory?.priority || 0;
                return bPriority - aPriority;
              });
          
            const storyMap = new Map(sortedStories.map(([path, module]) => {
              const baseName = path.split('/').pop().replace(/\.stories\.tsx$/, '');
              const meta = module.default || { title: baseName.split('_').join(' ') };
              return [baseName, { module, meta }];
            }));
          
            return storyMap;
          };
          
          const storyMap = createStoryMap(import.meta.glob('/${storyliteConfig.stories}', {eager: true}));
          
          console.log('Stories: ', Array.from(storyMap.keys()));
          
          export default storyMap
        `
      }

      if (id === moduleNames.userConfig) {
        return storyliteConfigImportCode
      }

      if (id === moduleNames.userUiStyles) {
        const cssFiles = storyliteConfig.styleImports?.ui || []

        return createCssBundleCode(cssFiles)
      }

      if (id === moduleNames.userSandboxStyles) {
        const cssFiles = storyliteConfig.styleImports?.sandbox || []

        return createCssBundleCode(cssFiles)
      }

      return null // otherwise, return null to let Vite handle the import as usual
    },
  }
}

export default storylitePlugin
